- name: Ensure hostname is setup correctly
  block:

    - name: Render /etc/hostname
      template:
        src: hostname.j2
        dest: /etc/hostname
        owner: root
        group: root
        mode: 'u=rw,g=r,o=r'
      become: yes

    - name: Render /etc/hosts
      template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 'u=rw,g=r,o=r'
      become: yes
