- copy:
  content: "{{ lookup('file', '/etc/apt/sources.list') | regex_replace('(https?:\/\/\w+\.ubuntu.com\/ubuntu)', apt_proxy_url, multiline=True, ignorecase=True) }}"
  dest: /etc/apt/sources.list
  become: yes
