- name: 'Unpacking ca_certs.tar.gz to /usr/local/share/ca-certificates/'
  unarchive:
    src: ca_certs.tar.gz
    dest: /usr/local/share/ca-certificates/
    group: root
    owner: root
    mode: 'u=rw,o=r,g=r'
  become: yes


- name: update-ca-certificates
  shell: update-ca-certificates
  become: yes
  register: output

- debug:
    msg: '{{ output.stdout }}'
