- name: Set the correct timezone
  shell: timedatectl set-timezone {{ timezone }}
  become: yes

- name: Remove password expiry for root user
  shell: chage -I -1 -m 0 -M 99999 -E -1 root
  become: yes

- name: Install apt packages
  apt:
    name: "{{ apt_packages }}"
    state: present
    autoclean: yes
    update_cache: yes
  become: yes

- name: Rebuild Trusted certificate store
  command: update-ca-certificates --fresh
  become: yes

- name: Install step (PKI/ACME client for private/internal CA)
  block:
    - name: Create temp dir
      tempfile:
        state: directory
        suffix: temp
      register: temp_dir

    - name: Download step-cli
      get_url:
        url: 'https://github.com/smallstep/cli/releases/download/v{{ step_cli_version }}/step-cli_{{ step_cli_version }}_amd64.deb'
        dest: '{{ temp_dir.path }}/step-cli.deb'
        mode: 'u+rwx'

    - name: Install step-cli
      apt:
        deb: '{{ temp_dir.path }}/step-cli.deb'
      become: yes

    - name: Remove temp dir
      file:
        path: "{{ temp_dir.path }}"
        state: absent
      when: temp_dir.path is defined

- name: Bootstrap the trust chain (installs Diesel-Net Root CA)
  shell: >
    step ca bootstrap --ca-url https://{{ ca_domain }} \
    --fingerprint {{ ca_fingerprint }} \
    --install -f
  become: yes
