- name: For each host, scan for its ssh public key
  delegate_to: localhost
  shell: "ssh-keyscan {{ item }},{{ lookup ('dig', item) }}"
  with_items: "{{ inventory_hostname }}"
  register: keyscan


- name: Remove the public host key in the '{{ ssh_known_hosts_file }}'
  delegate_to: localhost
  known_hosts:
    name: "{{ scan.item }}"
    state: "absent"
    path: "{{ ssh_known_hosts_file }}"
  loop_control:
    loop_var: scan
  loop: '{{ keyscan.results }}'


- name: Add/update the public host key in the '{{ ssh_known_hosts_file }}'
  delegate_to: localhost
  known_hosts:
    name: "{{ scan.item }}"
    key: "{{ scan.stdout }}"
    state: "present"
    path: "{{ ssh_known_hosts_file }}"
  #when: scan.rc == '0'
  loop_control:
    loop_var: scan
  loop: '{{ keyscan.results }}'
  
