- name: scan for hosts public keys
  delegate_to: localhost
  with_items: '{{ inventory_hostname }}'
  shell: "ssh-keyscan {{ item }},{{ lookup ('dig', item) }}"
  register: keyscan

- name: remove the public host key in the '{{ ssh_known_hosts_file }}'
  delegate_to: localhost
  loop: '{{ keyscan.results }}'
  loop_control:
    loop_var: result
  known_hosts:
    name: "{{ result.item }}"
    state: "absent"
    path: "{{ ssh_known_hosts_file }}"

- name: add/update the public host key in the '{{ ssh_known_hosts_file }}'
  delegate_to: localhost
  loop: '{{ keyscan.results }}'
  loop_control:
    loop_var: result
  known_hosts:
    name: "{{ result.item }}"
    key: "{{ result.stdout }}"
    state: "present"
    path: "{{ ssh_known_hosts_file }}"
