- name: scan for host's public keys
  delegate_to: localhost
  throttle: 1
  shell: "ssh-keyscan {{ inventory_hostname }}"
  register: keyscan

- debug:
    msg: '{{ keyscan.stdout }}'

- name: remove host's public keys from known_hosts file
  delegate_to: localhost
  throttle: 1
  known_hosts:
    name: "{{ inventory_hostname }}"
    state: "absent"
  when: keyscan.rc == 0

- name: add/update host's public keys in known_hosts file
  delegate_to: localhost
  throttle: 1
  known_hosts:
    name: "{{ inventory_hostname }}"
    key: "{{ keyscan.stdout }}"
    state: "present"
  when: keyscan.rc == 0
