- name: For each host, scan for its ssh public key
  delegate_to: localhost
  shell: "ssh-keyscan {{ item }},{{ lookup ('dig', item) }}"
  with_items: "{{ inventory_hostname }}"
  register: keyscan
  ignore_errors: yes

# TODO: If host unreachable, it could just be offline, check if key present in known-hosts and continue if so...



- name: Remove the public host key in the '{{ ssh_known_hosts_file }}'
  delegate_to: localhost
  known_hosts:
    name: "{{ result.item }}"
    state: "absent"
    path: "{{ ssh_known_hosts_file }}"
  loop_control:
    loop_var: result
  loop: '{{ keyscan.results }}'
  register: removal_attempt

- debug:
  msg: '{{ removal_attempt }}'


- name: Add/update the public host key in the '{{ ssh_known_hosts_file }}'
  delegate_to: localhost
  known_hosts:
    name: "{{ result.item }}"
    key: "{{ result.stdout }}"
    state: "present"
    path: "{{ ssh_known_hosts_file }}"
  loop_control:
    loop_var: result
  loop: '{{ keyscan.results }}'
  
