- name: scan for hosts public keys
  delegate_to: localhost
  with_items: '{{ inventory_hostname }}'
  shell: "ssh-keyscan {{ item }},{{ lookup ('dig', item) }}"
  register: keyscan
  ignore_errors: yes

- with_items: '{{ keyscan.results }}'
  debug:
    msg: '{{ item }}'
  
    

- name: remove the public host key from known_hosts file
  delegate_to: localhost
  when: item.rc == '0'
  # loop: '{{ keyscan.results }}'
  # loop_control:
  #   loop_var: result
  with_items: '{{ keyscan.results }}'
  known_hosts:
    name: "{{ item.item }}"
    state: "absent"

- name: add/update the public host key in known_hosts file
  delegate_to: localhost
  when: item.rc == '0'
  # loop: '{{ keyscan.results }}'
  # loop_control:
  #   loop_var: result
  with_items: '{{ keyscan.results }}'
  known_hosts:
    name: "{{ item.item }}"
    key: "{{ item.stdout }}"
    state: "present"
