- name: load known_hosts_path
  set_fact:
    known_hosts_path: '{{ lookup("env", "HOME") }}/.ssh/known_hosts'
- debug:
    msg: '{{ known_hosts_path }}'

# - name: delete known_hosts_file
#   delegate_to: localhost
#   shell:  'rm -rf {{ known_hosts_path }}'
#   become: yes

- name: scan for hosts public keys
  delegate_to: localhost
  with_items: '{{ inventory_hostname }}'
  shell: "ssh-keyscan {{ item }},{{ lookup ('dig', item) }}"
  register: keyscan
  ignore_errors: yes

- name: remove the public host key in the '{{ ssh_known_hosts_path }}'
  delegate_to: localhost
  loop: '{{ keyscan.results }}'
  loop_control:
    loop_var: result
  known_hosts:
    name: "{{ result.item }}"
    state: "absent"
    path: "{{ ssh_known_hosts_file }}"

- name: add/update the public host key in the '{{ ssh_known_hosts_path }}'
  delegate_to: localhost
  loop: '{{ keyscan.results }}'
  loop_control:
    loop_var: result
  known_hosts:
    name: "{{ result.item }}"
    key: "{{ result.stdout }}"
    state: "present"
    path: "{{ ssh_known_hosts_file }}"

- name: load known_hosts_file
  set_fact:
    known_hosts_file: '{{ lookup("file", known_hosts_path) }}'
- debug:
    msg: '{{ known_hosts_file }}'
