# failures from unreachable/offline hosts ignored
- name: scan for hosts public keys
  delegate_to: localhost
  with_items: '{{ inventory_hostname }}'
  shell: "ssh-keyscan {{ item }},{{ lookup ('dig', item) }}"
  register: keyscan
  ignore_errors: yes

- with_items: '{{ keyscan.results }}'
  debug:
    msg: '{{ item.rc }}'

# - name: remove the public host key from known_hosts file
#   delegate_to: localhost
#   loop: '{{ keyscan.results }}'
#   loop_control:
#     loop_var: result
#   when: result.rc == 0
#   known_hosts:
#     name: "{{ result.item }}"
#     state: "absent"

- name: add/update the public host key in known_hosts file
  delegate_to: localhost
  loop: '{{ keyscan.results }}'
  loop_control:
    loop_var: result
  when: result.rc == 0
  known_hosts:
    name: "{{ result.item }}"
    key: "{{ result.stdout }}"
    state: "present"
