- name: For each host, scan for its ssh public key
  delegate_to: localhost
  with_items: '{{ inventory_hostname }}'
  shell: "ssh-keyscan {{ item }},{{ lookup ('dig', item) }}"
  ignore_errors: yes
  register: keyscan

- name: 'print contents of {{ lookup("env", "HOME") }}/.ssh/known_hosts'
  shell: cat '{{ lookup("env", "HOME") }}/.ssh/known_hosts'
  delegate_to: localhost
  become: yes
  register: cat
- debug:
    msg: '{{ cat.stdout_lines }}'


- name: Check if {{ inventory_hostname }} still has the same IP
  delegate_to: localhost
  check_mode: yes
  with_items: '{{ inventory_hostname }}'
  replace:
    path: '{{ lookup("env", "HOME") }}/.ssh/known_hosts'
    regexp: '^({{ item | replace(".", "\.") }}),({{ lookup ("dig", item) | replace(".", "\.") }})(\s.*)'
    replace: '\1,5\.5\.6\.4\3'
  register: search
  failed_when: (search is changed) or (search is failed)


# - name:
#   delegate_to: localhost
#   when: result.rc == '0'
#   loop: '{{ keyscan.results }}'
#   loop_control:
#     loop_var: result
  

- name: Remove the public host key in the '{{ ssh_known_hosts_file }}'
  delegate_to: localhost
  when: result.rc == '0'
  loop: '{{ keyscan.results }}'
  loop_control:
    loop_var: result
  known_hosts:
    name: "{{ result.item }}"
    state: "absent"
    path: "{{ ssh_known_hosts_file }}"


- name: Add/update the public host key in the '{{ ssh_known_hosts_file }}'
  delegate_to: localhost
  when: result.rc == '0'
  loop: '{{ keyscan.results }}'
  loop_control:
    loop_var: result
  known_hosts:
    name: "{{ result.item }}"
    key: "{{ result.stdout }}"
    state: "present"
    path: "{{ ssh_known_hosts_file }}"
  

  
