- name: "Add and configure `{{ automation_user }}` user"
  user:
    name: "{{ automation_user }}"
    append: yes
    groups:
      - sudo
    create_home: yes
    expires: -1
    password_lock:  yes
    state: present
  become: yes

- name: "Configure Bash"
  user:
    name: automation
    shell: /bin/bash
  become: yes

- name: "Add `{{ automation_user }}` public ssh key to authorized_keys"
  authorized_key:
    user: "{{ automation_user }}"
    state: present
    key: "{{ automation_user_ssh_public_key }}"
    exclusive: yes
  become: yes

- name: "Remove password expiry for automation user"
  shell: chage -I -1 -m 0 -M 99999 -E -1 automation
  become: yes

- name: "Copy the `automation` sudoers configuration file over"
  copy:
    src: automation
    dest: /etc/sudoers.d/automation
    mode: 0440
    group: root
    owner: root
  become: yes

- name: "Configure Bash"
  user:
    name: automation
    shell: /bin/bash
  become: yes

- name: Allow port 22 (SSH)
  ufw:
    rule: allow
    port: '22'
    proto: any
  become: yes

- name: Reload Firewall and enable at boot
  ufw:
    state: enabled
    policy: deny
  become: yes
