- name: sudo apt update
  apt:
    update-cache: yes
  become: yes

- name: sudo apt upgrade -y
  apt:
    upgrade: safe
  become: yes

- name: Check to see if restart is required (to apply kernel updates)
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- debug:
    msg: 'reboot required: {{ reboot_required.stat.exists }}'
  changed_when: reboot_required.stat.exists and auto_reboot
  notify: reboot system
