- name: sudo apt update && sudo apt upgrade -y
  apt:
    update-cache: yes
    upgrade: safe
  become: yes

- block:

    - name: Check to see if restart is required (kernel updates)
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the system
      shell: sleep 5 && reboot
      become: yes
      async: 10
      poll: 0
      when: reboot_required.stat.exists

    - name: Wait for system to become reachable again
      wait_for_connection:
        delay: 60
        timeout: 300
      when: reboot_required.stat.exists

  when: auto_reboots
