- name: reboot the system
  shell: sleep 5 && reboot
  become: yes
  async: 10
  poll: 0
  listen: reboot system
  notify: wait to become reachable

- name: wait for system to become reachable again
  wait_for_connection:
    delay: 60
    timeout: 300
  listen: wait to become reachable

